name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Fetch listings
        run: npm run fetch:listings
        env:
          CS_FLOAT_API_KEY: ${{ secrets.CS_FLOAT_API_KEY }}

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
